program-synthesis-64:testmcts.py
	python2 testmcts.py 64 ../dataset/dataset1.txt syntia.64bit.middle.json 

json-transformation-64:
	python2 transformation.py syntia.64bit.middle.json 64bit.middle.txt

syntia-evaluation-64:
	python2 syntia-evaluation.py 64 64bit.middle.txt 64bit.result.txt 

