mba-simplify-1:
	python3 truthtable_simplify.py ../dataset/dataset1.txt

mba-simplify-8:
	python3 truthtable_simplify.py ../dataset/dataset2_8bit.txt

mba-simplify-16:
	python3 truthtable_simplify.py ../dataset/dataset2_16bit.txt

mba-simplify-32:
	python3 truthtable_simplify.py ../dataset/dataset2_32bit.txt

mba-simplify-64:
	python3 truthtable_simplify.py ../dataset/dataset2_64bit.txt
